### ISSUE TITLE
angular 9 typescript Uncaught TypeError: rtn.items.Count is not a function

### ISSUE THREAD

**Issue by syedadeel2** [kutyel/linq.ts#167]
I'm having the issue after compiling the typescript as soon I hit the button I got this error.

`if (rtn.items.Count() === 0) {
}`

no build errors, just on runtime also I can see that Webpack has included the Linqts module as well.

**Comment by kutyel** [comment]
This doesn't look as an error from the library, in your code, is `rtn.items` a `List<A>` of something? Or it is `rtn` the list? If that's the case you'll need to do `rtn.Count()`... If this is not the case please provide a failing test to the library so that we can fix the bug, but the `Count()` tests are passing fine 😄
