### ISSUE TITLE
Replace Webpack with Rollup

### ISSUE THREAD

**Issue by kutyel** [kutyel/linq.ts#86]
Should be fairly easy and improve performance as well, in the end I just want the browser build, and Webpack is an overkill just for that.

---
cc: @alexjoverm 😉

**Comment by Esslamb** [comment]
I can have a look at this tonight.

**Comment by alexjoverm** [comment]
I could provide some guidance here on the steps to take in order to produce multiple optimized bundles, aside from moving to Rollup:

 - It should make a UMD bundle, referred from the [`main`](https://github.com/kutyel/linq.ts/blob/master/package.json#L5) property in package.json. This is compatible with all module systems
 - A ES5 FESM, referred from the [`module`](https://github.com/alexjoverm/typescript-library-starter/blob/master/package.json#L7) property in package.json. Modern bundlers take this property if exists, so they can leverage tree shaking
 - The [`umd:main`](https://github.com/kutyel/linq.ts/blob/master/package.json#L6) have no idea what it is, but that's not use by npm, webpack or rollup, so I'd say remove it

As reference, [this is the issue](https://github.com/alexjoverm/typescript-library-starter/issues/35) I used for investigation in typescript-library-starter. Specially useful Alex Raudchmayer's article

**Comment by kutyel** [comment]
Thanks for all the intel! I would go ahead and encourage you to do your own PR, that way at least you will have one useful contribution in this year's hacktoberfest! 😜
