### ISSUE TITLE
Add minified dist file

### ISSUE THREAD

**Issue by kutyel** [kutyel/linq.ts#89]
Now that we are using Rollup, should be easy to output another file `linq.min.js` with the minified bundle as well 😄 

Happy #hacktoberfest! 🍻

**Comment by alexjoverm** [comment]
For CDN purposes this would come in handy, such as https://unpkg.com.

IMO this could be achieve better as a post-process step, using uglify on the umd bundle after it's generated, say running a `postbuild` command. Otherwise, doing it in Rollup (which is [not suggested](https://github.com/rollup/rollup/issues/799)) means to create the bundle several times an it's not its purpose.

**Comment by kutyel** [comment]
This will be achieved very soon by **microbundle** out-of-the-box when @_developit implements the TypeScript support 😉 👍
